# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - cache-{{ checksum "Pipfile.lock" }}
            - cache-

      - run:
          name: Install dependencies
          command: pipenv sync --dev

      - save_cache:
          key: cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache
      
      - run:
          name: run tests
          command: |
            pipenv run pytest --junitxml=test-reports/output.xml --cov chuda --cov-report xml

      - store_artifacts:
          path: test-reports/
          destination: tr1

      - store_artifacts:
          path: coverage.xml
          destination: tr1

      - store_test_results:
          path: test-reports/

      - run:
          name: upload coverage report
          command: |
            pipenv run codecov
          